# Generated by Django 5.1.4 on 2024-12-18 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
                ('malumot', models.TextField()),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='turlar/photo')),
            ],
        ),
        migrations.CreateModel(
            name='Gul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='gullar/photo')),
                ('malumot', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.turi')),
            ],
        ),
    ]
